# Generated by Django 5.0.6 on 2024-05-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(editable=False, unique_for_date='created', verbose_name='Слаг'),
        ),
    ]
